name: Museion Blue
favicon: null
layout_spectrum: 0.41034
typography_spectrum: 0.12322652526199818
title: 'Oleksander Bilyk: Selected Works'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#11141b'
    - '#7bb1fb'
    - '#bdfdfc'
    - '#5f90d5'
    - '#334b77'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
