name: Museion Blue
favicon: null
layout_spectrum: 0.4144219623412937
typography_spectrum: 0.12322652526199818
title: 'Oleksander Bilyk: Selected Works'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6754461419768631
  lightness: 0.31728499196469784
  saturation: 0.6721251090057194
  rhythmicContrast: 0.39539379091002047
purpose: []
